# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl